name: x509
description: Dart library for parsing and working with X.509 certificates.
version: 0.2.0-nullsafety.3
homepage: https://github.com/appsup-dart/x509

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  asn1lib: ^0.9.0-nullsafety.0
  quiver: ^3.0.0-nullsafety.3
  crypto_keys:
    git:
      url: git@github.com:Tougee/crypto_keys.git
      ref: feature/eddsa

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0

